version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - yarn config set cache-folder /root/.yarn
      - yarn install --frozen-lockfile  --prefer-offline
  pre_build:
    commands:
      # Clean entire monorepo and install dependent packages
      - ./node_modules/.bin/lerna bootstrap --ci --ignore-scripts --concurrency 4
  build:
    commands:
      # Build everything
      - echo Build started on `date`
      - ./node_modules/.bin/lerna run build --concurrency 4
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app.js
    - package.json
    - node_modules/**/*

# At this step, we instruct codebuild to cache all items that in the NPM Cache
# that we configured earlier
cache:
  paths:
    - node_modules
    - /root/.yarn/**/*
