version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
#      - yarn config set cache-folder /root/.yarn
#      - yarn install --frozen-lockfile  --prefer-offline
      # Temporarily using npm to fix the build. Should be updated to yarn later.
      - npm ci
  build:
    commands:
      # Build everything
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - npm run lint
      - npm run test
      - npm run test:e2e
artifacts:
  files:
    - '**/*'

# At this step, we instruct codebuild to cache all items that in the NPM Cache
# that we configured earlier
cache:
  paths:
    - node_modules
    - /root/.yarn/**/*
