version: 0.2

phases:
  pre_build:
    commands:
    - echo Installing source NPM dependencies...
    - yarn install
  build:
    commands:
    - echo Build started on `date`
    - yarn build
  post_build:
    commands:
    - echo Build completed on `date`
    - ls ./node_mod ules
artifacts:
  files:
    - app.js
    - package.json
    - node_modules/@sample/**/*
